# .github/release.yml
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - chore
          - dependencies
          - deployment
          - documentation
          - enhancement
          - feature
    - title: 🛠 Fixes
      labels:
        - bug
    - title: 🧹 Maintenance
      labels:
        - chore
    - title: 🔃 Dependencies
      labels:
        - dependencies
    - title: 🚀 Deployment
      labels:
        - deployment
    - title: 📖 Documentation
      labels:
        - documentation
    - title: ✨ Enhancements
      labels:
        - enhancement
    - title: 💡 Features
      labels:
        - feature