name: Deploy app insight 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Azure
        uses: azure/login@v2
        with:
            creds: >
                {
                    "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                    "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                    "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                    "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }
            enable-AzPSSession: true

    #   - name: replace scerets in Parameters
    #     run: |
    #         jq --arg sftp "${{ secrets.PIMFEED_COM_SFTP_KEY }}"\
    #         --arg accesskey "${{ secrets.PIMFEED_PIM_AWSS3_ACCESSKEYID }}"\
    #         --arg notification "${{secrets.NOTIFICATION_EMAILSERVICE_SECRET}}"\
    #         '.parameters.secrets.value[0].value = $sftp
    #         | .parameters.secrets.value[1].value = $accesskey
    #         | .parameters.secrets.value[2].value = $notification' \
    #         ./bicep/parameters/keyvault.json > ./bicep/updated-parameter/keyvault.json

      - name: Deploy Key Vault Bicep Template
        run: |
            appInsight=$(jq -r '.applicationInsights | tojson' ./bicep/parameters/appInsight.json)
            az deployment group create \
            --resource-group "komatsupoc" \
            --template-file ./appinsight.bicep \
            --parameters applicationInsights=$appInsight