name: Deploy DataFlow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

env: 
  adfName: $(jq -r ".adfName" ./bicep/parameters/${{ inputs.environment }}Parameters.json)
  resourceGroupName: $(jq -r ".resourceGroupName" ./bicep/parameters/${{ inputs.environment }}Parameters.json)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: >
                {
                  "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                  "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                  "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                  "tenantId":"${{ secrets.AZURE_TENANT_ID}}"
                }
          enable-AzPSSession: true

      - name: Read pipeline dataflow JSON files and deploy
        run: |
          # Ensure the correct path to the JSON files
          dataflow1=$(cat ./dataflow/dflow_SplitPimAdamPartsMediaExportMetadata.json)

          # Construct a JSON array with the dataflow contents
          dataflows=$(jq -n \
            --arg dataflow1 "$dataflow1" \
            '[
              {
                "name": "dflow_SplitPimAdamPartsMediaExportMetadata",
                "definition": $dataflow1 | fromjson
              }
            ]')

          # Deploy using Bicep (or ARM template)
          az deployment group create \
            --resource-group ${{ env.resourceGroupName }} \
            --template-file ./bicep/modules/dataflow.bicep \
            --parameters dataFactoryName=${{ env.adfName }} \
            --parameters dataflows="$dataflows"