name: Deploy ADF LinkedService

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get install jq

    - name: Print Environment
      run: |
        echo ${{ inputs.environment }}
        echo ${{ secrets.AZURE_CLIENT_ID }}
        echo ${{ secrets.AZURE_CLIENT_SECRET }}
        echo ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        echo ${{ secrets.AZURE_TENANT_ID }}
        echo ${{ github.env.TESTEV}}

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true