name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
    contents: read
    pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false

      - name: clean labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            bug
            chore
            dependencies
            deployment
            documentation
            enhancement
            feature

      - name: add bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'bugfix:') }}
        with:
          labels: bug

      - name: add chore label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'chore:') }}
        with:
          labels: chore
      
      - name: add dependencies label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'depend:') }}
        with:
          labels: dependencies

      - name: add deployment label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'deploy:') }}
        with:
          labels: deployment
      
      - name: add documentation label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'doc:') }}
        with:
          labels: documentation

      - name: add enhancement label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'enhance:') }}
        with:
          labels: enhancement
        
      - name: add feature label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'feat:') }}
        with:
          labels: feature