name: Deploy Service Bus and Storage Resources

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
            creds: >
                {
                    "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                    "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                    "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                    "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }
            enable-AzPSSession: true
      
      # Deploy Bicep template
      - name: Deploy Bicep Template
        run: |
          serviceBusName=$(jq -r '.serivceBus[0].serviceBusName' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          location=$(jq -r '.serivceBus[0].location' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          queues=$(jq -c '.serivceBus[0].queues' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          topics=$(jq -c '.serivceBus[0].topics' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          tags=$(jq -c '.serivceBus[0].tags' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          
          # Deploy using Bicep
          az deployment group create \
            --resource-group "komatsupoc" \
            --template-file ./servicebus.bicep \
            --parameters serviceBusName="$serviceBusName" \
                          location="$location" \
                          queues="$queues" \
                          topics="$topics" \
                          tags="$tags"

