name: Deploy Azure Storage Table

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

env:
  storageAccountName: $(jq -r ".storageAccountName" ./bicep/parameters/${{ inputs.environment }}Parameters.json)
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Azure
        uses: azure/login@v2
        with:
            creds: >
                {
                    "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                    "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                    "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                    "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }
            enable-AzPSSession: true

      
  
      - name: Deploy Bicep Template
        run: |
              # Extract values using jq
              #resourceGroupName=$(jq -r '.resourceGroupName' ./bicep/parameters/${{inputs.environment}}storageTable.json)
              storageAccounts=$(jq -r '.storageAccounts' ./bicep/parameters/${{inputs.environment}}storageTable.json)
          
              # Deploy using az CLI, passing the parameters as JSON arrays
              az deployment group create \
                --resource-group "komatsupoc" \
                --template-file ./storageTable.bicep \
                --parameters storageAccounts="$storageAccounts" \
          
          
      # - name: Insert rows into the Azure Table
      #   run: |
      #       STORAGE_ACCOUNT_NAME="<your-storage-account-name>"
      #       TABLE_NAME="mytable"
      #       CONNECTION_STRING=$(az storage account show-connection-string --name $STORAGE_ACCOUNT_NAME --query connectionString --output tsv)

      #       # Insert rows into the table
      #       az storage entity insert --connection-string $CONNECTION_STRING --table-name $TABLE_NAME --entity PartitionKey=part1 RowKey=1 name=row1 value=data1
      #       az storage entity insert --connection-string $CONNECTION_STRING --table-name $TABLE_NAME --entity PartitionKey=part1 RowKey=2 name=row2 value=data2
      #       az storage entity insert --connection-string $CONNECTION_STRING --table-name $TABLE_NAME --entity PartitionKey=part1 RowKey=3 name=row3 value=data3
      #       az storage entity insert --connection-string $CONNECTION_STRING --table-name $TABLE_NAME --entity PartitionKey=part1 RowKey=4 name=row4 value=data4