name: Deploy Azure Storage Table

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Azure
        uses: azure/login@v2
        with:
            creds: >
                {
                    "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                    "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                    "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                    "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }
            enable-AzPSSession: true

        
      - name: Deploy Bicep Template
        run: |
              # Check if Bicep template exists
              if [ ! -f ./storageTable.bicep ]; then
                echo "Bicep template not found!"
                exit 1
              fi
          
              # Deploy using the Bicep template
              az deployment group create \
                --resource-group komatasu-poc \
                --template-file ./storageTable.bicep
          
