name: Versioning and Tagging

on:
  workflow_call:
    inputs:
      change-type:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  contents: write

jobs:
  versioning:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag and determine version change type 
        if: ${{ inputs.environment == 'prod' }}
        id: versioning
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          VERSION=${LAST_TAG#v}
          MAJOR=$(echo $VERSION | cut -d '.' -f 1)
          MINOR=$(echo $VERSION | cut -d '.' -f 2)
          PATCH=$(echo $VERSION | cut -d '.' -f 3)

          changetype=${{ inputs.change-type }}
          if echo "$changetype" | grep -i "Major"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif echo "$changetype" | grep -i "Minor"; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif echo "$changetype" | grep -i "Patch"; then
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push new version tag
        if: ${{ inputs.environment == 'prod' && github.ref_name == 'main' }}
        run: |
          git config --global user.email "souvikg90@gmail.com"
          git config --global user.name "sghosh"
          git tag -a $NEW_VERSION -m "Release version $NEW_VERSION"
          git push origin $NEW_VERSION
